Override DNA/RNA pipeline configs
chrovis-genomon/genomon-api pull request #9
Opened 2020-09-10 13:58 UTC by alumi

This PR adds an optional functionality for overriding DNA/RNA pipeline configs.

I added an option `:allow-override-config?` to the `:genomon-api/handler` module in the duct config.
This option controls whether handlers optionally accept `:config` body parameter in requests which override default configs.
In other words, configs are overridden iff `:allow-override-config?` is truthy and a request has `:config` body parameter.

This PR also includes dependency upgrades and extraction of config files from uberjar.

2020-09-14 02:25 UTC, athos requested changes
Thank you for adding this convenient feature! 🙌 This must be useful to develop a new feature and improve existing features across multiple Genomon modules.

I have left two comments, so please check them out.

2020-09-14 02:25 UTC, athos commented on src/genomon_api/handler/pipelines/rna.clj
> +                    run (exec/run-rna-pipeline executor id config body)]
The current implementation requires the overriding config map to always include the `instance-option`, which consists of AWS subnet ID, security group ID and so on (If you omit those, Genomon will fail to submit ECS tasks).

I think it would be more useful if the overriding config automatically inherits the `instance-option` value from `dna-` / `rna-option`, rather than having to submit AWS internal IDs every time we just want to override a part of the Genomon configs.

```suggestion
                    run (exec/run-rna-pipeline executor id
                                               (assoc-in config [:general :instance-option]
                                                         (get-in rna-config [:general :instance-option]))
                                               body)]
```

2020-09-14 13:30 UTC, alumi commented on src/genomon_api/handler/pipelines/rna.clj
> +                    run (exec/run-rna-pipeline executor id config body)]
Thank you! Fixed in 640041d.
I've confirmed it doesn't throw errors by adding the `--dryrun` option to the `genomon_pipeline_cloud`.
Maybe we need more tests around the docker executor...

2020-09-14 13:30 UTC, alumi commented on src/genomon_api/handler/pipelines/rna.clj
> +                    run (exec/run-rna-pipeline executor id config body)]
That sounds like a good idea 👍 Added in eb39116. Thank you!

2020-09-15 01:24 UTC, athos approved these changes
Thank you for updating your code! LGTM 👍

2020-09-15 01:24 UTC, merged

2020-09-15 01:50 UTC, alumi commented
@athos Thank you for your review! 🙏